### ISSUE TITLE
Kiwi browser doesn't support hcaptcha 

### ISSUE THREAD

**Issue by karanrawat2qrawat377** [kiwibrowser/src#148]
Whenever i try to solve hcaptcha, I am not able to touch images it automatically close the hcaptcha

**Comment by kiwibrowser** [comment]
Fixed @ https://github.com/kiwibrowser/src/commit/256d2dc82ab2ebb51095ab028d7c217b8e5e791e

**Comment by anonqoder** [comment]
Just tested https://github.com/kiwibrowser/src/releases and the bug still happens
