### ISSUE TITLE
[BUG] Address bar is white when system dark mode is enabled

### ISSUE THREAD

**Issue by ItsBluuu** [kiwibrowser/src#308]
For some reason, the address bar changes to white when selecting it while dark mode is enabled. Currently using a Pixel 4a.
Before selecting the bar:
![Screenshot (4 Feb 2021 18_55_26)](https://user-images.githubusercontent.com/78471815/106935065-31126880-671b-11eb-85c3-0a611e62994c.png)
After selection:
![Screenshot (4 Feb 2021 18_55_48)](https://user-images.githubusercontent.com/78471815/106935092-366fb300-671b-11eb-897b-732c978d69dd.png)

**Comment by kiwibrowser** [comment]
Hello,

Thank you for reporting the issue about the incorrect colors in the omnibox,
Just to clarify, you are using the Dark / night mode of Android or a Substratum theme ?

**Comment by ItsBluuu** [comment]
Hi,
I was using the built-in dark mode for Android 11 but I issue was resolved after downloading the last security patch for some reason.

**Comment by ItsBluuu** [comment]
Ok, after trying a few things, this bug only appears when force dark mode (in the Developer options) is enabled.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
